name: venv_VLabApp
channels:
    - conda-forge
dependencies:
    - aicsimageio==4.14.0
    - cellpose==3.1.0
    - imageio[ffmpeg]==2.27.0
    - matplotlib-base==3.10.1
    - micro_sam==1.6.1
    - napari==0.5.5
    - nd2==0.10.1
    - numpy==1.26.4
    - ome-types==0.6.0
    - pandas==2.2.3
    - py-opencv==4.11.0=headless*
    - pyqt==5.15.9
    - pystackreg==0.2.8
    - python==3.11.11
    - python-igraph==0.11.8
    - pytorch==2.6.0
    - roifile==2024.5.24
    - scikit-image==0.20.0
    - scipy==1.15.2
    - tifffile==2022.4.8
    - torchvision==0.21.0
